### ISSUE TITLE
Unit tests - specifications needed

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/layers-store#6]
This library lacks unit tests which will allow us to confidently update library dependencies.
We need to specify the tests that need to be written.

@adam-collins Can I ask in the first instance you just do a quick brain dump of things that should be tested ?

**Comment by djtfmartin** [comment]
Linked to 

https://github.com/AtlasOfLivingAustralia/biocache-service/issues/381

**Comment by ansell** [comment]
We can't switch all Java testsuites over to JUnit-5, but there are no tests here, so we can start off with it. JUnit-5 is supported in recent versions of ala-parent-pom so shouldn't be difficult to get up and running.
